 ``7-base_geometry test file``


Using ``integer_validator`` function



	>>> BaseGeometry = __import__('7-base_geometry').BaseGeometry
	>>> tbg = BaseGeometry()
	>>> tbg.integer_validator("my_int", 12)
	>>> tbg.integer_validator("width", 89)
	>>> tbg.integer_validator("name", "John")
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
	>>> tbg.integer_validator("float_n", 5.23)
	Traceback (most recent call last):
        ...
	TypeError: float_n must be an integer
	>>> tbg.integer_validator("float_n", float("inf"))
	Traceback (most recent call last):
        ...
	TypeError: float_n must be an integer
	>>> tbg.integer_validator("float_n", float("-inf"))
	Traceback (most recent call last):
        ...
	TypeError: float_n must be an integer
	>>> tbg.integer_validator("boolean", True)
	Traceback (most recent call last):
        ...
	TypeError: boolean must be an integer
	>>> tbg.integer_validator("age", 0)
	Traceback (most recent call last):
        ...
	ValueError: age must be greater than 0
	>>> tbg.integer_validator("distance", -4)
	Traceback (most recent call last):
        ...
	ValueError: distance must be greater than 0
	>>> tbg.integer_validator("missing1")
	Traceback (most recent call last):
        ...
	TypeError: integer_validator() missing 1 required positional argument: 'value'
	>>> tbg.integer_validator()
	Traceback (most recent call last):
        ...
	TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'
	>>> tbg.integer_validator("name", None)
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
	>>> tbg.area()
	Traceback (most recent call last):
	...
	Exception: area() is not implemented
	>>> tbg.area("aaa")
	Traceback (most recent call last):
	...
	TypeError: area() takes 1 positional argument but 2 were given
	>>> tbg.integer_validator("name", 2+5j)
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
	>>> tbg.integer_validator("name", [1, 2])
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
	>>> tbg.integer_validator("name", (1, 2))
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
	>>> tbg.integer_validator("name", {"a": 8})
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
	>>> tbg.integer_validator("name", {2, 8})
	Traceback (most recent call last):
        ...
	TypeError: name must be an integer
